import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";

const Home: NextPage = () => {
  const [user, setUser] = useState<{ userName: string; role: string }>();
  const fetchUser = async () => {
    const user = await fetch("/.auth/me");
    const data = await user.json();
    setUser({
      userName: data?.clientPrincipal?.userDetails,
      role: data?.clientPrincipal?.userRoles,
    });
    // console.log(data);
    // return data;
  };
  useEffect(() => {
    fetchUser();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>SWA to be deployed on Azure SWA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="text-blue-400 text-xl">This is our main title</div>
        <div>{JSON.stringify(user, null, 2)}</div>
        {JSON.stringify(user) === JSON.stringify({}) ? (
          <a href="/login" className="text-green-400 p-2 px-4 underline">
            Click here to Login
          </a>
        ) : (
          <a href="/logout" className="text-red-400 p-2 px-4 underline">
            Click here to Logout
          </a>
        )}
      </main>
    </div>
  );
};

export default Home;
